BEGIN;

CREATE TABLE tp_tasks(
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  status VARCHAR(255) NOT NULL,
  source VARCHAR(255) NOT NULL,
  process VARCHAR(255) NULL DEFAULT NULL,
  created DATETIME,
  started DATETIME NULL DEFAULT NULL,
  finished DATETIME NULL DEFAULT NULL,
  data TEXT NOT NULL,
  report TEXT NULL DEFAULT NULL
);

COMMIT;
